version: "3"

services:
  
  web:
    build: .
    container_name: tixxety_api
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=tixxety_db
      - DB_USER=user
      - DB_PASS=password
      - DATABASE_URL=postgresql://user:password@db:5432/tixxety_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: tixxety_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tixxety_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  

  pgadmin:
    image: dpage/pgadmin4
    container_name: tixxety_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db


volumes:
  pgdata:
  pgadmin_data: