"""create tickets table

Revision ID: 41b99ea23640
Revises: 202261436436
Create Date: 2025-10-29 20:30:27.060850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41b99ea23640'
down_revision: Union[str, Sequence[str], None] = '202261436436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('RESERVED', 'PAID', 'EXPIRED', name='ticket_status'),
               nullable=False)
    op.alter_column('tickets', 'event_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tickets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tickets', 'event_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('RESERVED', 'PAID', 'EXPIRED', name='ticket_status'),
               nullable=True)
    # ### end Alembic commands ###
