"""edit users and events tables

Revision ID: 5946abef8ed7
Revises: 41b99ea23640
Create Date: 2025-10-29 21:02:39.665792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5946abef8ed7'
down_revision: Union[str, Sequence[str], None] = '41b99ea23640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('street', sa.String(length=300), nullable=True))
    op.add_column('events', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('country', sa.String(length=100), nullable=True))
    op.drop_column('events', 'venue')
    op.add_column('users', sa.Column('street', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'state')
    op.drop_column('users', 'city')
    op.drop_column('users', 'street')
    op.add_column('events', sa.Column('venue', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.drop_column('events', 'country')
    op.drop_column('events', 'state')
    op.drop_column('events', 'city')
    op.drop_column('events', 'street')
    # ### end Alembic commands ###
